name: update fe-toolkit-doc

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0' # 获取所有历史，以便复制

      - name: Setup Git
        run: |
          git config --global user.email "1226355793@qq.com"
          git config --global user.name "SliverKeigo"

      - name: Clone target repository
        run: git clone https://${{ secrets.PUSH }}@github.com/SliverKeigo/SliverKeigo.github.io.git target_repo

      - name: Sync files
        run: |
          rsync -a --delete ./ target_repo/ --exclude .git
          cd target_repo
          git add .
          git status
          git commit -m "Sync files from source to SliverKeigo/SliverKeigo.github.io" || echo "No changes to commit"
          git push origin master
